# General
site_name: Shippable Documentation
repo_url: https://github.com/lekhab

# Paths
docs_dir: sources
theme_dir: theme/shippable

# Pages
pages:
  - [index.md, Getting Started, About Shippable]
  - [sign_up.md, Getting Started, 'Sign up for Shippable']
  - [account_settings.md, Getting Started, 'Account Settings']
  - [build_quickstart.md, Getting Started, 'Quick Start: Run your first build']
  - [formations_quickstart.md, Getting Started, 'Quick Start: Set up your first Formation']

  - [ci_overview.md, Shippable CI, Overview]
  - [basic_flow.md, Shippable CI, Basic Build Flow]
  - [build_config.md, Shippable CI, Build Configuration]
  - [lighthouse.md, Shippable CI, Lighthouse]
  - [ci_userguide.md, Shippable CI, User Guide]
  - [languages/index.md, Shippable CI, Language help]
  - [languages/images.md, Shippable CI, Build images]

  - [formations_overview.md, Shippable Formations, Overview]
  - [formations_userguide.md, Shippable Formations, User Guide]
  - [formations_faq.md, Shippable Formations, Formations FAQ]

  - [deployment/index.md, Deployment, Overview]
  - [deployment/heroku.md, Deployment, Heroku]
  - [deployment/beanstalk.md, Deployment, Amazon Elastic Beanstalk]
  - [deployment/opswork.md, Deployment, AWS OpsWorks]
  - [deployment/appengine.md, Deployment, Google App Engine]
  - [deployment/openshift.md, Deployment, Red Hat OpenShift]
  - [deployment/digitalocean.md, Deployment, DigitalOcean]
  - [deployment/codedeploy.md, Deployment, AWS CodeDeploy]

  - [docker_registries.md, Docker, Overview]
  - [dockerhub.md, Docker, Docker Hub]
  - [gcr.md, Docker, Google Container Registry]

  - [api.md, Reference, API]
  - [faq.md, Reference, FAQ]

