# General
site_name: Shippable Documentation
repo_url: https://github.com/Shippable

# Paths
docs_dir: sources
theme_dir: theme/shippable

# Pages
pages:
  - [index.md, Getting Started, Overview]
  - [start.md, Getting Started, Running your first build]
  - [config.md, Getting Started, Important concepts]

  - [yml_overview.md, Configuration, Config overview]
  - [yml_reference.md, Configuration, YML reference]
  - [languages/index.md, Configuration, Language help]
  - [languages/images.md, Configuration, Build images]

  - [deployment/index.md, Deployment, Continuous Deployment]
  - [deployment/heroku.md, Deployment, Heroku]
  - [deployment/beanstalk.md, Deployment, Amazon Elastic Beanstalk]
  - [deployment/opswork.md, Deployment, AWS OpsWorks]
  - [deployment/appengine.md, Deployment, Google App Engine]
  - [deployment/openshift.md, Deployment, Red Hat OpenShift]
  - [deployment/digitalocean.md, Deployment, DigitalOcean]
  - [deployment/codedeploy.md, Deployment, AWS CodeDeploy]

  - [docker.md, Docker, Docker Hub]
  - [gcr.md, Docker, Google Container Registry]

  - [api.md, API]

  - [glossary.md, Glossary]

  - [faq.md, FAQ]
